/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as common from "@nestjs/common";
import * as swagger from "@nestjs/swagger";
import { isRecordNotFoundError } from "../../prisma.util";
import * as errors from "../../errors";
import { Request } from "express";
import { plainToClass } from "class-transformer";
import { ApiNestedQuery } from "../../decorators/api-nested-query.decorator";
import { CheckService } from "../check.service";
import { CheckCreateInput } from "./CheckCreateInput";
import { Check } from "./Check";
import { CheckFindManyArgs } from "./CheckFindManyArgs";
import { CheckWhereUniqueInput } from "./CheckWhereUniqueInput";
import { CheckUpdateInput } from "./CheckUpdateInput";
import { SimilarityReportFindManyArgs } from "../../similarityReport/base/SimilarityReportFindManyArgs";
import { SimilarityReport } from "../../similarityReport/base/SimilarityReport";
import { SimilarityReportWhereUniqueInput } from "../../similarityReport/base/SimilarityReportWhereUniqueInput";

export class CheckControllerBase {
  constructor(protected readonly service: CheckService) {}
  @common.Post()
  @swagger.ApiCreatedResponse({ type: Check })
  async createCheck(@common.Body() data: CheckCreateInput): Promise<Check> {
    return await this.service.createCheck({
      data: {
        ...data,

        document: data.document
          ? {
              connect: data.document,
            }
          : undefined,
      },
      select: {
        id: true,
        createdAt: true,
        updatedAt: true,

        document: {
          select: {
            id: true,
          },
        },

        checkedBy: true,
        checkDate: true,
        similarityScore: true,
        report: true,
      },
    });
  }

  @common.Get()
  @swagger.ApiOkResponse({ type: [Check] })
  @ApiNestedQuery(CheckFindManyArgs)
  async checks(@common.Req() request: Request): Promise<Check[]> {
    const args = plainToClass(CheckFindManyArgs, request.query);
    return this.service.checks({
      ...args,
      select: {
        id: true,
        createdAt: true,
        updatedAt: true,

        document: {
          select: {
            id: true,
          },
        },

        checkedBy: true,
        checkDate: true,
        similarityScore: true,
        report: true,
      },
    });
  }

  @common.Get("/:id")
  @swagger.ApiOkResponse({ type: Check })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  async check(
    @common.Param() params: CheckWhereUniqueInput
  ): Promise<Check | null> {
    const result = await this.service.check({
      where: params,
      select: {
        id: true,
        createdAt: true,
        updatedAt: true,

        document: {
          select: {
            id: true,
          },
        },

        checkedBy: true,
        checkDate: true,
        similarityScore: true,
        report: true,
      },
    });
    if (result === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return result;
  }

  @common.Patch("/:id")
  @swagger.ApiOkResponse({ type: Check })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  async updateCheck(
    @common.Param() params: CheckWhereUniqueInput,
    @common.Body() data: CheckUpdateInput
  ): Promise<Check | null> {
    try {
      return await this.service.updateCheck({
        where: params,
        data: {
          ...data,

          document: data.document
            ? {
                connect: data.document,
              }
            : undefined,
        },
        select: {
          id: true,
          createdAt: true,
          updatedAt: true,

          document: {
            select: {
              id: true,
            },
          },

          checkedBy: true,
          checkDate: true,
          similarityScore: true,
          report: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }

  @common.Delete("/:id")
  @swagger.ApiOkResponse({ type: Check })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  async deleteCheck(
    @common.Param() params: CheckWhereUniqueInput
  ): Promise<Check | null> {
    try {
      return await this.service.deleteCheck({
        where: params,
        select: {
          id: true,
          createdAt: true,
          updatedAt: true,

          document: {
            select: {
              id: true,
            },
          },

          checkedBy: true,
          checkDate: true,
          similarityScore: true,
          report: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }

  @common.Get("/:id/similarityReports")
  @ApiNestedQuery(SimilarityReportFindManyArgs)
  async findSimilarityReports(
    @common.Req() request: Request,
    @common.Param() params: CheckWhereUniqueInput
  ): Promise<SimilarityReport[]> {
    const query = plainToClass(SimilarityReportFindManyArgs, request.query);
    const results = await this.service.findSimilarityReports(params.id, {
      ...query,
      select: {
        id: true,
        createdAt: true,
        updatedAt: true,
        matchPercentage: true,
        matchSnippet: true,

        check: {
          select: {
            id: true,
          },
        },

        matchedDocument: true,
      },
    });
    if (results === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return results;
  }

  @common.Post("/:id/similarityReports")
  async connectSimilarityReports(
    @common.Param() params: CheckWhereUniqueInput,
    @common.Body() body: SimilarityReportWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      similarityReports: {
        connect: body,
      },
    };
    await this.service.updateCheck({
      where: params,
      data,
      select: { id: true },
    });
  }

  @common.Patch("/:id/similarityReports")
  async updateSimilarityReports(
    @common.Param() params: CheckWhereUniqueInput,
    @common.Body() body: SimilarityReportWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      similarityReports: {
        set: body,
      },
    };
    await this.service.updateCheck({
      where: params,
      data,
      select: { id: true },
    });
  }

  @common.Delete("/:id/similarityReports")
  async disconnectSimilarityReports(
    @common.Param() params: CheckWhereUniqueInput,
    @common.Body() body: SimilarityReportWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      similarityReports: {
        disconnect: body,
      },
    };
    await this.service.updateCheck({
      where: params,
      data,
      select: { id: true },
    });
  }
}
