/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as graphql from "@nestjs/graphql";
import { GraphQLError } from "graphql";
import { isRecordNotFoundError } from "../../prisma.util";
import { MetaQueryPayload } from "../../util/MetaQueryPayload";
import { Check } from "./Check";
import { CheckCountArgs } from "./CheckCountArgs";
import { CheckFindManyArgs } from "./CheckFindManyArgs";
import { CheckFindUniqueArgs } from "./CheckFindUniqueArgs";
import { DeleteCheckArgs } from "./DeleteCheckArgs";
import { CheckService } from "../check.service";
@graphql.Resolver(() => Check)
export class CheckResolverBase {
  constructor(protected readonly service: CheckService) {}

  async _checksMeta(
    @graphql.Args() args: CheckCountArgs
  ): Promise<MetaQueryPayload> {
    const result = await this.service.count(args);
    return {
      count: result,
    };
  }

  @graphql.Query(() => [Check])
  async checks(@graphql.Args() args: CheckFindManyArgs): Promise<Check[]> {
    return this.service.checks(args);
  }

  @graphql.Query(() => Check, { nullable: true })
  async check(
    @graphql.Args() args: CheckFindUniqueArgs
  ): Promise<Check | null> {
    const result = await this.service.check(args);
    if (result === null) {
      return null;
    }
    return result;
  }

  @graphql.Mutation(() => Check)
  async deleteCheck(
    @graphql.Args() args: DeleteCheckArgs
  ): Promise<Check | null> {
    try {
      return await this.service.deleteCheck(args);
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new GraphQLError(
          `No resource was found for ${JSON.stringify(args.where)}`
        );
      }
      throw error;
    }
  }
}
